name: Deploy Web Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Godot
      uses: chickensoft-games/setup-godot@v1
      with:
        version: 4.4.1
        use-dotnet: false
    
    - name: Import project
      run: |
        godot --headless --import
    
    - name: Install web export templates
      run: |
        mkdir -p ~/.local/share/godot/export_templates/4.4.1.stable/
        wget -q https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz
        unzip -q Godot_v4.4.1-stable_export_templates.tpz
        mv templates/* ~/.local/share/godot/export_templates/4.4.1.stable/
    
    - name: Build for web
      run: |
        mkdir -p build/web
        godot --headless --export-release "Web" build/web/index.html
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/web

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
